'use client';

import { useActionState } from 'react';
import { useFormStatus } from 'react-dom';
import { issueEnrollmentAction } from '@/app/owner/actions';
import { IDLE } from '@/lib/action-state';
import type { BranchView } from '@/lib/api/organization';
import { Alert, AlertDescription } from '@/components/ui/alert';
import { Button } from '@/components/ui/button';
import { Card, CardContent } from '@/components/ui/card';
import { Input } from '@/components/ui/input';
import { Field } from '@/components/field';
import { NativeSelect } from '@/components/native-select';
import { CircleAlertIcon } from 'lucide-react';

function SubmitButton() {
  const { pending } = useFormStatus();

  return (
    <Button type="submit" disabled={pending}>
      {pending ? 'Inatengeneza...' : 'Tengeneza msimbo · Issue code'}
    </Button>
  );
}

/**
 * Issuing the one-time enrollment code.
 *
 * This form has its own component rather than using `ActionForm` because of
 * what it returns: the code is shown **once**. The backend stores only a
 * SHA-256 hash and no later request can fetch it, so the screen has to say so
 * plainly and the owner has to write it down before navigating away. Nothing
 * here stores it either — it lives in React state until the page changes, and
 * then it is gone in the same way it is gone from the server.
 */
export function EnrollmentForm({ branches }: { branches: BranchView[] }) {
  const [state, formAction] = useActionState(issueEnrollmentAction, IDLE);

  return (
    <div className="flex flex-col gap-4">
      {state.secret ? (
        <Card role="status" className="border-primary/30 bg-success-muted/40">
          <CardContent className="flex flex-col items-center gap-3 pt-5 text-center">
            <p className="text-xs font-semibold text-muted-foreground">
              Msimbo wa &ldquo;{state.secret.deviceName}&rdquo;
            </p>

            <p className="tabular select-all rounded-lg bg-card px-4 py-2 text-2xl font-bold tracking-[0.2em] shadow-sm">
              {state.secret.code}
            </p>

            {/*
              The same code, for a phone that is standing right here.
              `dangerouslySetInnerHTML` is the only way to inline an SVG string,
              and it is safe for exactly one reason worth writing down: this
              markup is generated by our own backend from a code our own backend
              minted moments earlier. It is never user input, never stored, and
              never round-tripped through anything. If that ever stops being
              true, this stops being safe.
            */}
            <div
              className="rounded-lg bg-white p-2 [&>svg]:block [&>svg]:size-40"
              role="img"
              aria-label={`Msimbo wa ${state.secret.deviceName} kama QR · Enrollment code as a QR code`}
              dangerouslySetInnerHTML={{ __html: state.secret.qrSvg }}
            />

            <p className="text-xs text-muted-foreground">
              Au isome kwa simu · Or scan it with the phone: gusa <strong>Soma msimbo</strong> kwenye
              skrini ya usajili.
            </p>

            <Alert variant="warning" className="text-left">
              <CircleAlertIcon />
              <AlertDescription>
                <strong className="font-semibold">Andika sasa.</strong> Msimbo huu hauonyeshwi tena
                kamwe — Shoprex huhifadhi alama yake tu, si msimbo wenyewe. Write it down now: this
                code is never shown again, and Shoprex stores only its hash.
              </AlertDescription>
            </Alert>

            <p className="text-xs text-muted-foreground">
              Unaisha · Expires {new Date(state.secret.expiresAt).toLocaleString('en-GB')}.
              Ukiupoteza, tengeneza mwingine.
            </p>
          </CardContent>
        </Card>
      ) : null}

      <form action={formAction} className="flex flex-col gap-3">
        <div className="grid gap-3 sm:grid-cols-2">
          <Field htmlFor="enroll-branch" label="Tawi · Branch this phone belongs to">
            <NativeSelect id="enroll-branch" name="branchId" required>
              {branches.map((branch) => (
                <option key={branch.id} value={branch.id}>
                  {branch.name}
                </option>
              ))}
            </NativeSelect>
          </Field>

          <Field htmlFor="enroll-name" label="Jina la simu · What to call this phone">
            <Input id="enroll-name" name="deviceName" required placeholder="Simu ya kaunta" />
          </Field>
        </div>

        <SubmitButton />

        {state.error ? (
          <p
            role="alert"
            className="flex items-start gap-2 rounded-lg border border-destructive/30 bg-destructive/10 px-3 py-2 text-sm"
          >
            <CircleAlertIcon className="mt-0.5 size-4 shrink-0 text-destructive" />
            {state.error}
          </p>
        ) : null}
      </form>
    </div>
  );
}
